In [1]:
import numpy as np

In [16]:
a = np.random.rand(4,3,2)

In [17]:
print(a)
a.shape

[[[0.47052757 0.55240926]
  [0.56168515 0.17406032]
  [0.3005985  0.99838474]]

 [[0.25812089 0.78599616]
  [0.65313297 0.86101835]
  [0.69276399 0.45507622]]

 [[0.0642156  0.36037348]
  [0.76287106 0.86829137]
  [0.09008311 0.14496054]]

 [[0.36741323 0.32164129]
  [0.01900045 0.26905442]
  [0.10636561 0.35855052]]]


(4, 3, 2)

In [27]:
b = a.reshape(a.shape[0], -1).T 
# same as b = a.reshape(2 * 3, 4)

In [28]:
print(b)
b.shape

[[0.47052757 0.25812089 0.0642156  0.36741323]
 [0.55240926 0.78599616 0.36037348 0.32164129]
 [0.56168515 0.65313297 0.76287106 0.01900045]
 [0.17406032 0.86101835 0.86829137 0.26905442]
 [0.3005985  0.69276399 0.09008311 0.10636561]
 [0.99838474 0.45507622 0.14496054 0.35855052]]


(6, 4)

In [33]:
c = np.random.rand(1,3)
print(np.dot(c,c.T), np.multiply(c,c), c)

[[0.25649897]] [[0.01769853 0.20653159 0.03226885]] [[0.13303582 0.45445746 0.17963533]]
